spring.application.name=audit-service
server.port=8084
spring.jackson.serialization.indent-output=true

app.database.host=localhost
app.database.port=5432
app.database.name=thesisdb
app.database.username=aiymserjan
app.database.password=Aiym0404
app.database.url=jdbc:postgresql://localhost:5432/thesisdb

app.messaging.rabbit.enabled=true
app.messaging.rabbit.exchange=thesis.workflow.exchange
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
