spring.application.name=thesis-system
spring.jackson.serialization.indent-output=true
server.port=8080

app.database.host=localhost
app.database.port=5432
app.database.name=thesisdb
app.database.username=aiymserjan
app.database.password=Aiym0404
app.database.url=jdbc:postgresql://localhost:5432/thesisdb
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

app.messaging.rabbit.enabled=true
app.messaging.rabbit.exchange=thesis.workflow.exchange
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
app.auth.default-password=123456
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
