spring.application.name=workflow-service
server.port=8082
spring.jackson.serialization.indent-output=true
spring.config.import=optional:classpath:application.properties
app.security.jwt.secret=${JWT_SECRET:replace-this-with-a-long-random-secret-key-for-user-service}
app.security.jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:3600}

app.messaging.rabbit.enabled=${RABBIT_ENABLED:true}
app.messaging.rabbit.exchange=thesis.workflow.exchange
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USERNAME:guest}
spring.rabbitmq.password=${RABBIT_PASSWORD:guest}
