app.database.host=${DB_HOST:localhost}
app.database.port=${DB_PORT:5432}
app.database.name=${DB_NAME:thesisdb}
app.database.username=${DB_USERNAME:aiymserjan}
app.database.password=${DB_PASSWORD:Aiym0404}
app.database.url=jdbc:postgresql://${app.database.host}:${app.database.port}/${app.database.name}
spring.datasource.url=${app.database.url}
spring.datasource.username=${app.database.username}
spring.datasource.password=${app.database.password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=public
