spring.application.name=api-gateway
server.port=8080
spring.jackson.serialization.indent-output=true

app.services.user.base-url=${USER_SERVICE_URL:http://localhost:8081}
app.services.workflow.base-url=${WORKFLOW_SERVICE_URL:http://localhost:8082}
app.services.notification.base-url=${NOTIFICATION_SERVICE_URL:http://localhost:8083}
app.services.audit.base-url=${AUDIT_SERVICE_URL:http://localhost:8084}
